// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: image.sql

package model

import (
	"context"

	"github.com/gofrs/uuid"
)

const genImageCreate = `-- name: GenImageCreate :one
insert into generated_images (url) values ($1) returning id
`

func (q *Queries) GenImageCreate(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, genImageCreate, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
