// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: image.sql

package model

import (
	"context"

	"github.com/gofrs/uuid"
)

const genImageCreate = `-- name: GenImageCreate :one
insert into generated_images (url, user_id) values ($1, $2) returning id
`

type GenImageCreateParams struct {
	Url    string
	UserID uuid.UUID
}

func (q *Queries) GenImageCreate(ctx context.Context, arg GenImageCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, genImageCreate, arg.Url, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
